'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("guinget.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ---------------------------------------------------------------.
        '''</summary>
        Friend ReadOnly Property AboutSeparator() As String
            Get
                Return ResourceManager.GetString("AboutSeparator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unofficial GUI for Microsoft&apos;s Windows Package Manager (winget).
        '''Kinda like Synaptic, but for Windows. Not associated with either
        '''Microsoft or the Synaptic project. Microsoft does not endorse guinget.
        '''winget is Copyright (c) Microsoft Corporation. All rights reserved.
        '''
        '''You can get the source code for guinget from
        '''https://github.com/DrewNaylor/guinget
        '''
        '''libguinget is used for things like loading the package list and uses the Apache License 2.0.
        '''libguinget Copyright (C) 2020-2022 Drew Naylor.
        '''
        '''libsc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property AboutWindowCopyrightsAndStuff() As String
            Get
                Return ResourceManager.GetString("AboutWindowCopyrightsAndStuff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search terms,Action.
        '''</summary>
        Friend ReadOnly Property DefaultSidebarList() As String
            Get
                Return ResourceManager.GetString("DefaultSidebarList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search terms,Action,Status,Custom filters,Categories,Source,Architecture.
        '''</summary>
        Friend ReadOnly Property HiddenSidebarList() As String
            Get
                Return ResourceManager.GetString("HiddenSidebarList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copied from https://github.com/dotnet/efcore/blob/main/LICENSE.txt
        '''This also appears to be the same as the one from here: https://github.com/dotnet/runtime/blob/main/LICENSE.TXT
        '''The MIT License (MIT)
        '''
        '''Copyright (c) .NET Foundation and Contributors
        '''
        '''All rights reserved.
        '''
        '''Permission is hereby granted, free of charge, to any person obtaining a copy
        '''of this software and associated documentation files (the &quot;Software&quot;), to deal
        '''in the Software without restriction, including without limitation the rights [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LicenseForMicrosoftDataSqlite() As String
            Get
                Return ResourceManager.GetString("LicenseForMicrosoftDataSqlite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copied from https://github.com/dotnet/corefx/blob/master/LICENSE.TXT in case it&apos;ll ever be different.
        '''The MIT License (MIT)
        '''
        '''Copyright (c) .NET Foundation and Contributors
        '''
        '''All rights reserved.
        '''
        '''Permission is hereby granted, free of charge, to any person obtaining a copy
        '''of this software and associated documentation files (the &quot;Software&quot;), to deal
        '''in the Software without restriction, including without limitation the rights
        '''to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LicenseForNumericsBuffersAndMemory() As String
            Get
                Return ResourceManager.GetString("LicenseForNumericsBuffersAndMemory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copied from https://www.nuget.org/packages/YamlDotNet/11.2.1/license
        '''Copyright (c) 2008, 2009, 2010, 2011, 2012, 2013, 2014 Antoine Aubry and contributors
        '''
        '''Permission is hereby granted, free of charge, to any person obtaining a copy of
        '''this software and associated documentation files (the &quot;Software&quot;), to deal in
        '''the Software without restriction, including without limitation the rights to
        '''use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
        '''of the Software, and to permit perso [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LicenseForYamlDotNet() As String
            Get
                Return ResourceManager.GetString("LicenseForYamlDotNet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Microsoft.Data.Sqlite depends on SQLitePCLRaw.core, SQLitePCLRaw.bundle_e_sqlite3,
        '''SQLitePCLRaw.lib.e_sqlite3, and SQLitePCLRaw.provider.dynamic_cdecl, which all are
        '''under the Apache License, Version 2.0.
        '''GitHub page for these dependencies: https://github.com/ericsink/SQLitePCL.raw
        '''These dependencies are Copyright 2014-2022 SourceGear, LLC.
        '''SQLitePCLRaw is a fork of SQLitePCL, which was a library MS Open Tech released
        '''on Codeplex. That library also falls under the Apache License, Version 2.0.
        '''See bel [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MicrosoftDataSqliteDependencies() As String
            Get
                Return ResourceManager.GetString("MicrosoftDataSqliteDependencies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Relevant text copied from https://github.com/ericsink/SQLitePCL.raw/blob/master/NOTICE.TXT
        '''----------------------------------------------------------------
        '''Copyright on SQLitePCL.raw
        '''----------------------------------------------------------------
        '''
        '''Version prior to 2.0 were labeled with the copyright owned by
        '''Zumero.  In 2.0, this changed to SourceGear.  There is no legal
        '''distinction, as Zumero is simply a dba name for SourceGear.
        '''
        '''And in either case, the open source license remains the same,
        '''Apac [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQLitePCLRawLicenses() As String
            Get
                Return ResourceManager.GetString("SQLitePCLRawLicenses", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
