'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("guinget.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ---------------------------------------------------------------.
        '''</summary>
        Friend ReadOnly Property AboutSeparator() As String
            Get
                Return ResourceManager.GetString("AboutSeparator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unofficial GUI for Microsoft&apos;s Windows Package Manager (winget).
        '''Kinda like Synaptic, but for Windows. Not associated with either
        '''Microsoft or the Synaptic project. Microsoft does not endorse guinget.
        '''winget is Copyright (c) Microsoft Corporation. All rights reserved.
        '''
        '''You can get the source code for guinget from
        '''https://github.com/DrewNaylor/guinget
        '''
        '''libguinget is used for things like loading the package list and uses the Apache License 2.0.
        '''libguinget Copyright (C) 2020-2022 Drew Naylor.
        '''
        '''libsc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property AboutWindowCopyrightsAndStuff() As String
            Get
                Return ResourceManager.GetString("AboutWindowCopyrightsAndStuff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search terms,Action.
        '''</summary>
        Friend ReadOnly Property DefaultSidebarList() As String
            Get
                Return ResourceManager.GetString("DefaultSidebarList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search terms,Action,Status,Custom filters,Categories,Source,Architecture.
        '''</summary>
        Friend ReadOnly Property HiddenSidebarList() As String
            Get
                Return ResourceManager.GetString("HiddenSidebarList", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
